# Agua
AGUA_MINIMA = 10
AGUA_INICIAL_PLANTACION = 500

# Riego
TEMP_MIN_RIEGO = 8
TEMP_MAX_RIEGO = 15
HUMEDAD_MAX_RIEGO = 50

# Cultivos
SUPERFICIE_PINO = 2.0
AGUA_INICIAL_PINO = 2
AGUA_INICIAL_OLIVO = 5
SUPERFICIE_OLIVO = 3.0
AGUA_INICIAL_ZANAHORIA = 0
SUPERFICIE_ZANAHORIA = 0.15
ABSORCION_SEASONAL_VERANO = 5
AGUA_INICIAL_LECHUGA = 1
SUPERFICIE_LECHUGA = 0.2
